### ISSUE TITLE
Webpack Error

### ISSUE THREAD

**Issue by Nkr1shna** [chriscourses/voyager#2]
I get this error after running webpack, probably some import error. Can some one help me fix it?

```
ERROR in ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./src/scss/style.scss
Module build failed:
    @include breakpoint($screen-sm-min) {
            ^
      No mixin named breakpoint

Backtrace:
        src/scss/global/util.scss:12
      in /home/kr1shna/Desktop/BookSwap/src/scss/global/util.scss (line 12, column 14)
 @ ./src/scss/style.scss 4:14-170
 @ ./src/global.js

ERROR in ./src/scss/style.scss
Module build failed: ModuleBuildError: Module build failed:
    @include breakpoint($screen-sm-min) {
            ^
      No mixin named breakpoint

Backtrace:
        src/scss/global/util.scss:12
      in /home/kr1shna/Desktop/BookSwap/src/scss/global/util.scss (line 12, column 14)
    at runLoaders (/home/kr1shna/Desktop/BookSwap/node_modules/webpack/lib/NormalModule.js:195:19)
    at /home/kr1shna/Desktop/BookSwap/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/kr1shna/Desktop/BookSwap/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/kr1shna/Desktop/BookSwap/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/home/kr1shna/Desktop/BookSwap/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (/home/kr1shna/Desktop/BookSwap/node_modules/neo-async/async.js:7921:18)
    at options.error (/home/kr1shna/Desktop/BookSwap/node_modules/node-sass/lib/index.js:294:32)
 @ ./src/scss/style.scss
 @ ./src/global.js
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/lib/loader.js!src/scss/style.scss:
       [0] ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./src/scss/style.scss 266 bytes {0} [built] [failed] [1 error]

    ERROR in ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./src/scss/style.scss
    Module build failed:
        @include breakpoint($screen-sm-min) {
                ^
          No mixin named breakpoint

    Backtrace:
        src/scss/global/util.scss:12
          in /home/kr1shna/Desktop/BookSwap/src/scss/global/util.scss (line 12, column 14)
```

**Comment by christopher4lis** [comment]
Fixed with the most recent update: **Update styling to include new branding.**
