### ISSUE TITLE
setup on ubuntu

### ISSUE THREAD

**Issue by frank3427** [chriscourses/voyager#6]
I am seeing the following warnings
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
/usr/bin/voyager -> /usr/lib/node_modules/voyager-cli/bin/voyager.js
+ voyager-cli@0.1.4
added 380 packages from 200 contributors in 24.853s

**Comment by frank3427** [comment]
also issue with 
ecc@azure-edge4:~/eccportal$ sudo voyager start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ecc/.npm/_logs/2019-04-19T22_18_37_536Z-debug.log
ecc@azure-edge4:~/eccportal$ voyager start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ecc/.npm/_logs/2019-04-19T22_19_03_646Z-debug.log
ecc@azure-edge4:~/eccportal$ ^C
ecc@azure-edge4:~/eccportal$
--------here is the log----
ecc@azure-edge4:~/eccportal$ more /home/ecc/.npm/_logs/2019-04-19T22_19_03_646Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.9.0
3 info using node@v8.16.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:280:12
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd /home/ecc/eccportal
6 verbose Linux 4.15.0-47-generic
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
8 verbose node v8.16.0
9 verbose npm  v6.9.0
10 error missing script: start
11 verbose exit [ 1, true ]
ecc@azure-edge4:~/eccportal$

**Comment by frank3427** [comment]
I can get it to run if i do not create a project --auth
it is failing if build project with --auth
